#include <stdio.h>
#include "gmp.h"
#include "ncr.h"

int main(int argc, char** argv){
FILE* f1 = fopen("ncrValues.h", "wb");
if(f1 == NULL){
    printf("ncrValues.h can be opened for writing. Exiting...\n");
}

int ncrMapMax = 1000;
mpz_t bV; mpz_init(bV);
int i = 0, j = 0, n = 20000, r = 0, bitLen = 0;
float revDensity = 0;

fprintf(f1, "/* Generated by generateNCR.c */\n");
fprintf(f1, "#include <stdio.h>\n");
fprintf(f1, "#define NCR_MAP_MAX %d\n", ncrMapMax);
fprintf(f1, "//n is %d\n", n);
fprintf(f1, "float ncrMap[NCR_MAP_MAX] = {\n");

if(ncrMapMax == 100){
for(i = 1; i <= 100; i++){
    mpz_bin_uiui(bV, n, i*(n/100));
    bitLen = mpz_sizeinbase(bV, 2);
    revDensity = (float)(bitLen * 100) / (float)n;
    if(i == 100){
        fprintf(f1, "\t\t\t\t %.2f \t//%d percent density\n", revDensity, i);
    } else {
        fprintf(f1, "\t\t\t\t %.2f, \t//%d percent density\n", revDensity, i);
    }
}
}

if(ncrMapMax == 1000){
for(i = 0; i < 100; i++){
    for(j = 1; j <= 10; j++){
        mpz_bin_uiui(bV, n, ((float)i + (float)(j)/(float)10)*(n/100));
        bitLen = mpz_sizeinbase(bV, 2);
        revDensity = (float)(bitLen * 100) / (float)n;
        if(i == 100-1 && j == 10){
            fprintf(f1, "\t\t\t\t %.2f \t//%.2f percent density\n", revDensity, ((float)i + (float)(j)/(float)10));
        } else {
            fprintf(f1, "\t\t\t\t %.2f, \t//%.2f percent density\n", revDensity, ((float)i + (float)(j)/(float)10));
        }
    }
}
}

fprintf(f1, "\t\t\t};\n");
fclose(f1);
}
